CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "email" varchar(255) UNIQUE,
  "email_verified_at" timestamp,
  "password" varchar(255),
  "phone" varchar(20) UNIQUE,
  "avatar" varchar(255),
  "status" varchar(20) DEFAULT 'active',
  "remember_token" varchar(100),
  "is_admin" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "addresses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "full_name" varchar(150),
  "phone" varchar(20),
  "address_line_1" varchar(255),
  "address_line_2" varchar(255),
  "landmark" varchar(255),
  "city" varchar(100),
  "state" varchar(100),
  "country" varchar(100),
  "postal_code" varchar(20),
  "address_type" varchar(30),
  "is_default" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150),
  "slug" varchar(200) UNIQUE,
  "description" text,
  "image" varchar(255),
  "status" boolean DEFAULT true,
  "sort_order" int DEFAULT 0,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" bigint NOT NULL,
  "name" varchar(255),
  "slug" varchar(255) UNIQUE,
  "short_description" text,
  "description" text,
  "main_ingredient" varchar(255),
  "ingredients" text,
  "shelf_life" varchar(100),
  "storage_instructions" text,
  "dispatch_time" varchar(100),
  "image_alt" varchar(255),
  "average_rating" decimal(3,2) DEFAULT 0,
  "total_reviews" int DEFAULT 0,
  "is_available" boolean DEFAULT true,
  "is_hidden" boolean DEFAULT false,
  "featured" boolean DEFAULT false,
  "best_seller" boolean DEFAULT false,
  "new_arrival" boolean DEFAULT false,
  "seasonal" boolean DEFAULT false,
  "meta_title" varchar(255),
  "meta_description" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "product_variants" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "weight" varchar(50),
  "price_minor" bigint NOT NULL,
  "stock_quantity" int NOT NULL DEFAULT 0,
  "low_stock_threshold" int DEFAULT 5,
  "sku" varchar(120) UNIQUE,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "product_images" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "image" varchar(255),
  "alt_text" varchar(255),
  "sort_order" int DEFAULT 1,
  "is_primary" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "carts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "session_id" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "cart_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" bigint NOT NULL,
  "product_variant_id" bigint NOT NULL,
  "quantity" int DEFAULT 1,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "wishlists" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "wishlist_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wishlist_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_number" varchar(50) UNIQUE,
  "user_id" bigint,
  "address_id" bigint,
  "guest_email" varchar(255),
  "guest_phone" varchar(20),
  "subtotal_minor" bigint NOT NULL,
  "shipping_fee_minor" bigint NOT NULL DEFAULT 0,
  "gst_amount_minor" bigint NOT NULL DEFAULT 0,
  "total_minor" bigint NOT NULL,
  "shipping_full_name" varchar(150),
  "shipping_phone" varchar(20),
  "shipping_address_line_1" varchar(255),
  "shipping_address_line_2" varchar(255),
  "shipping_landmark" varchar(255),
  "shipping_city" varchar(100),
  "shipping_state" varchar(100),
  "shipping_country" varchar(100),
  "shipping_postal_code" varchar(20),
  "payment_status" varchar(30) DEFAULT 'pending',
  "order_status" varchar(50) DEFAULT 'placed',
  "tracking_number" varchar(100),
  "courier_name" varchar(100),
  "shipped_at" timestamp,
  "delivered_at" timestamp,
  "gift_order" boolean DEFAULT false,
  "gift_message" text,
  "notes" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "order_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "product_variant_id" bigint NOT NULL,
  "product_name" varchar(255),
  "weight" varchar(50),
  "unit_price_minor" bigint NOT NULL,
  "quantity" int,
  "total_price_minor" bigint NOT NULL,
  "gst_rate_applied" decimal(5,2),
  "gst_amount_minor" bigint DEFAULT 0,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "payment_method" varchar(50),
  "gateway" varchar(100),
  "gateway_order_id" varchar(255),
  "gateway_payment_id" varchar(255),
  "amount_minor" bigint NOT NULL,
  "currency" varchar(10) DEFAULT 'INR',
  "status" varchar(30),
  "paid_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "payment_transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_id" bigint NOT NULL,
  "transaction_type" varchar(50),
  "gateway_transaction_id" varchar(255),
  "amount_minor" bigint NOT NULL,
  "gateway_event_id" varchar(255) UNIQUE,
  "response_code" varchar(100),
  "response_message" text,
  "gateway_response" text,
  "created_at" timestamp
);

CREATE TABLE "order_status_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "status" varchar(50),
  "changed_by" bigint,
  "notes" text,
  "created_at" timestamp
);

CREATE TABLE "reviews" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "product_id" bigint NOT NULL,
  "order_id" bigint,
  "rating" int,
  "review" text,
  "verified_purchase" boolean DEFAULT false,
  "legacy_review" boolean DEFAULT false,
  "status" varchar(30) DEFAULT 'pending',
  "approved_by" bigint,
  "approved_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "review_images" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "review_id" bigint NOT NULL,
  "image" varchar(255),
  "created_at" timestamp
);

CREATE TABLE "blog_posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "slug" varchar(255) UNIQUE,
  "cover_image" varchar(255),
  "excerpt" text,
  "content" text,
  "author_id" bigint,
  "status" varchar(20) DEFAULT 'draft',
  "published_at" timestamp,
  "meta_title" varchar(255),
  "meta_description" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "hero_banners" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "desktop_image" varchar(255),
  "mobile_image" varchar(255),
  "title" varchar(255),
  "subtitle" text,
  "button_text" varchar(100),
  "button_url" varchar(255),
  "is_active" boolean DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "homepage_sections" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "section_key" varchar(100) UNIQUE,
  "title" varchar(255),
  "subtitle" text,
  "is_visible" boolean DEFAULT true,
  "display_order" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "testimonials" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "review_id" bigint,
  "customer_name" varchar(255),
  "rating" int,
  "testimonial" text,
  "is_featured" boolean DEFAULT false,
  "display_order" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "pages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "slug" varchar(255) UNIQUE,
  "content" text,
  "status" varchar(20) DEFAULT 'published',
  "meta_title" varchar(255),
  "meta_description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "settings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "setting_key" varchar(150) UNIQUE,
  "setting_value" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "title" varchar(255),
  "message" text,
  "type" varchar(50),
  "is_read" boolean DEFAULT false,
  "created_at" timestamp
);

CREATE TABLE "audit_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "action" varchar(100),
  "table_name" varchar(100),
  "record_id" bigint,
  "old_values" jsonb,
  "new_values" jsonb,
  "ip_address" varchar(50),
  "user_agent" text,
  "created_at" timestamp
);

CREATE TABLE "tax_rates" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" bigint,
  "hsn_code" varchar(20),
  "rate_percent" decimal(5,2) NOT NULL,
  "effective_from" date NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "shipping_rules" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "min_order_amount_minor" bigint DEFAULT 0,
  "free_above_amount_minor" bigint,
  "flat_fee_minor" bigint NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "email_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient_email" varchar(255) NOT NULL,
  "email_type" varchar(100),
  "reference_type" varchar(50),
  "reference_id" bigint,
  "status" varchar(30) DEFAULT 'sent',
  "sent_at" timestamp,
  "created_at" timestamp
);

ALTER TABLE "addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlist_items" ADD FOREIGN KEY ("wishlist_id") REFERENCES "wishlists" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "wishlist_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment_transactions" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_status_history" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_status_history" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "review_images" ADD FOREIGN KEY ("review_id") REFERENCES "reviews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "blog_posts" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "testimonials" ADD FOREIGN KEY ("review_id") REFERENCES "reviews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tax_rates" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;
